### ISSUE TITLE
Back Button After Logging In

### ISSUE THREAD

**Issue by JEVietti** [willgoishi/DealBreaker#3]
If the user has logged in and exits the app goes back to the title screen which is good, but if the user presses the back button after that it jumps back to the previous part of the app stack, so a possible solution is to override the OnBackPressed() in the InitialScreen class or clear the app stack when exiting the app; possibly both.

**Comment by AndresFelipeVargas** [comment]
Fixed. Had to change the userNavigation onBackPressed() action when the user pressed the yes key. Instead of going to the login activity through an intent, I just ended the activity. This way there is no back trail (also since we were technically done with that activity). Updated code is up on github.
